### PR TITLE
Update Node to 4.2.4

### PR DESCRIPTION
**Pull request by MariusRumpf**

### CODE REVIEW

**Comment by MariusRumpf** [comment]
Drone test does stop at `$ git checkout -qf FETCH_HEAD` I assume you are aware of that already.

**Comment by StefanScherer** [comment]
Now this time Drone is prepared to update it faster :smile:

**Comment by StefanScherer** [comment]
I'll restart the Drone build after the armv6l version is available at https://nodejs.org/dist/v4.2.4/

**Comment by MariusRumpf** [comment]
That was a fast! Alright.

**Pull request merged**
