### PR TITLE
Update Node to 4.3.0 and 5.6.0

### PR DESCRIPTION
**Pull request by MariusRumpf**

### CODE REVIEW

**Comment by StefanScherer** [comment]
LGTM. Thanks again ;-)

**Comment by MariusRumpf** [comment]
Glad to help, but it seems the 5.6.0 build did not succeed. 

```
sha256sum: standard input: no properly formatted SHA256 checksum lines found
```

When I request https://nodejs.org/dist/v5.6.0/SHASUMS256.txt.asc there is still no checksum for `node-v5.6.0-linux-armv6l.tar.gz`. That might be the problem.

**Comment by StefanScherer** [comment]
Yes, the `armv6l` will be published after the official release as they are compiling on RPi1...
We have to wait a little.

**Comment by MariusRumpf** [comment]
Ah I see the binary are also missing. Okay we wait a litte.

**Comment by MariusRumpf** [comment]
There we go, now they are online.

**Comment by StefanScherer** [comment]
I’ve restarted the build…

**Pull request merged**
